# -*- coding: utf-8 -*-
"""karmaşık_ağ_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-2zgzJGqiRSpLcOQaABgMYHwfAfQzHbC
"""

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd

edges=pd.read_csv("InputFileEdges.csv")
nodes=pd.read_csv("InputFileNodes.csv")

nodes["id"]=nodes["id"]
edges["from"]=edges["from"]
edges["to"]=edges["to"]

edges=edges.drop_duplicates()

G=nx.Graph()
G.add_edges_from(edges[["from","to"]].itertuples(index=False,name=None))

plt.figure(figsize=(8,6))
nx.draw(G,with_labels=True, node_size=300, font_size=8)
plt.title("Yönsüz Ağ")
plt.show()

G_directed=nx.DiGraph()
G_directed.add_edges_from(edges[["from", "to"]].itertuples(index=False, name=None))

plt.figure(figsize=(8, 6))
nx.draw(G_directed, with_labels=True, node_size=300, font_size=8, arrows=True)
plt.title("Yönlü Ağ")
plt.show()

toplam=0
for node_name in G.nodes():
  print(f"{node_name} düğümün derecesi: {G.degree(node_name)}")
  toplam+=G.degree(node_name)
print(f"Ortalama : {toplam/len(nodes)}")

plt.hist([G.degree(n) for n in G.nodes()])

deg_centrality = nx.degree_centrality(G)

closeness_centrality=nx.closeness_centrality(G)

betweenness_centrality = nx.betweenness_centrality(G)

eigenvector_centrality = nx.eigenvector_centrality(G)

katz_centrality = nx.katz_centrality(G, alpha=0.1, beta=1.0)

pagerank_centrality = nx.pagerank(G)

from networkx .algorithms.community import greedy_modularity_communities
communities=greedy_modularity_communities(G)
modularity=nx.algorithms.community.quality.modularity(G,communities)
print("Modularity:",modularity)

density = nx.density(G)
print("Density",density)

avg_clustering = nx.average_clustering(G)
print("Average clustering:", avg_clustering)

if nx.is_connected(G):
  diameter=nx.diameter(G)
else:
  diameter="Graf bağlantılı değil"
print("Diameter:",diameter)

degrees = [d for n, d in G.degree()]
degree_values = sorted(set(degrees))
degree_counts = [degrees.count(x) for x in degree_values]
plt.figure()
plt.plot(degree_values, degree_counts, marker="o")
plt.title("Derece Dağılımı")
plt.xlabel("Derece")
plt.ylabel("Düğüm Sayısı")
plt.grid(True)
plt.show()

kritik_kopru=sorted(betweenness_centrality.items(),key=lambda x:x[1],reverse=True)[:5]
print("En kritik 5 Köprü:",kritik_kopru)

kritik_lider=sorted(pagerank_centrality.items(),key=lambda x:x[1],reverse=True)[:5]
print("En kritik 5 Lider:",kritik_lider)

in_degrees=dict(G_directed.in_degree())
out_degrees=dict(G_directed.out_degree())

plt.figure()
plt.hist(list(in_degrees.values()))
plt.title("Giriş Derecesi Dağılımı")
plt.show()

plt.figure()
plt.hist(list(out_degrees.values()))
plt.title("Çıkış Derecesi Dağılımı")
plt.show()

son=sorted(pagerank_centrality.items(),key=lambda x:x[1],reverse=True)[:3]
son_nodes=[x[0] for x in son]

G2=G.copy()
G2.remove_nodes_from(son_nodes)
plt.figure()
nx.draw(G2,with_labels=True,node_color='orange')
plt.title("En Güçlü 3 Düğüm Kaldırıldıktan Sonraki Ağ")
plt.show()

print("Kaldırılan düğümler:", son_nodes)